### PR TITLE
WIP: Add Office floor

### PR DESCRIPTION
**Pull request by abjose**
Welcome to the office. We're so glad to have you on the team!

This is definitely NOT ready for thorough review (badly needs cleanup and rebasing, among many other issues) but figured I'd send it out to start getting your ideas and feedback. The code is full of spoilers, so don't look before you've tried it (unless you want to). This branch currently always spawns you in the office when you start a game.

### CODE REVIEW

**Review by flosincapite — COMMENTED** [review]
This is really fun! I like how the coffee machine and copier are NPCs. It kind of foreshadows stuff later, but it also means we should consider how to handle situations like fighting, where it doesn't make sense to say, "Coffee machine makes no hostile motion."

I really, really, REALLY like caressing the copier, but I managed to spawn multiple writhing masses in the meeting room that way. Dunno if that's intended.

I also noticed that the item descriptions didn't keep track with the names you could use in commands. So even though I had "ichor," I had to <spoiler>do something with "coffee" at some point</spoiler>. The hacky fix is to use a class-level variable to hold the underlying names, but that involves digging deep into the implementation of item. I think there's a better way, but I gotta think about it.

But yeah, I like it!

**Comment by abjose** [comment]
> This is really fun! I like how the coffee machine and copier are NPCs. It kind of foreshadows stuff later, but it also means we should consider how to handle situations like fighting, where it doesn't make sense to say, "Coffee machine makes no hostile motion."

Do you think it would make sense to have a separate entity type, like "EnvironmentEntity" or something?

> I really, really, REALLY like caressing the copier, but I managed to spawn multiple writhing masses in the meeting room that way. Dunno if that's intended.

I'm almost reluctant to fix this but definitely not intended

> I also noticed that the item descriptions didn't keep track with the names you could use in commands. So even though I had "ichor," I had to do something with "coffee" at some point. 

Yeah, definitely don't like this part. I could add "ichor" to the other allowable names for coffee? With the risk of that being a spoiler.

**Comment by xmunoz** [comment]
Do you think you'll get a chance to clean  this up any time soon @abjose? If not, I can take it over next week.

**Comment by xmunoz** [comment]
I'm going to close this in favor of the newer PR #136, which incorporates the new whimsylib dependency and creates a transition from the cathedral to the office.

**Comment by abjose** [comment]
Thank you!! Sorry for going AWOL

**Pull request closed without merging**
