### PR TITLE
Adds event polling back to commands that once had it, then lost it.

### PR DESCRIPTION
**Pull request by flosincapite**

### CODE REVIEW

**Comment by xmunoz** [comment]
I'm a bit confused about why the `poll` functionality needed to be extracted from `when`, since it needs to get called whenever `when` is called. Can you explain the rationale?

**Comment by flosincapite** [comment]
> I'm a bit confused about why the `poll` functionality needed to be extracted from `when`, since it needs to get called whenever `when` is called. Can you explain the rational?

Because if every call to `when` also polls, we end up polling multiple times when each command is run.

I originally collapsed them into a single function because adventurelib's `when` did some weird argument validation that constrained my ability to separate them. When I wanted to decorate a function with multiple commands, I used `adventurelib.when` for all but the final `when` in the chain; I used the polling implementation for the final one.

I'd rather make it clear when a command needs to poll and when it doesn't. Now that we are free to have a separate poll function, let's do that; it's how I would have implemented things in the first place had it been possible.

**Comment by xmunoz** [comment]
This is fine for now, but in the future I think we should reassess this design. Maybe the commands should be sub-classes of a base class that takes care of all this set up and tear down.

**Review by xmunoz — APPROVED** [review]

**Comment by flosincapite** [comment]
> This is fine for now, but in the future I think we should reassess this design. Maybe the commands should be sub-classes of a base class that takes care of all this set up and tear down.

Yeah, I completely agree. Now that we're pretty much at feature parity, we can start to redesign stuff, and I agree that there are better ways to define commands.

**Pull request merged**
